### ISSUE TITLE
Implement Multiple App Launches

### ISSUE THREAD

**Issue by steven-snider** [bill-long/EventLogExpert#107]
Frequently attempt to debug server issues by opening both App and System event logs and reviewing time and events side-by-side.  Please enable the app for multi-launch.

**Comment by bill-long** [comment]
This is already a thing. If you go to File->Open and open another log, it opens in a new window. If you have set up a file association, double-clicking another evtx does the same thing. It opens in a new window, leaving the existing log open. Is this not working for you?

**Comment by steven-snider** [comment]
You’re absolutely right.  Sorry, not a method of multi-app load I’m used to with EventViewerPro, so didn’t try.  Thanks for the response.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
