### ISSUE TITLE
EventLogExpert does not work on Windows 11 OS

### ISSUE THREAD

**Issue by rajravin** [bill-long/EventLogExpert#138]
EventLogExpert does not work with Windows 11 OS, We just get blank page once we open the Event log file.
![EventLogExpert](https://user-images.githubusercontent.com/92773577/137845223-cf6c9f04-8e4d-401f-8511-2a8ce2cff6a9.png)

**Comment by nascar3000** [comment]
PS issue with "EventLogReader" resolved in KB5007262

PS C:\> $reader = New-Object System.Diagnostics.Eventing.Reader.EventLogReader("C:\some.evtx", "FilePath")
PS C:\> $events = while ($null -ne ($ev = $reader.ReadEvent())) { $ev }
PS C:\> $events | ? { $_.Id -eq $null } | Measure
Count    : 0
Average  :
Sum      :
Maximum  :
Minimum  :
Property :

Installed KB and tested but EventLogExpert still shows nothing.

**Comment by bill-long** [comment]
Excellent! Thanks for letting me know.
